name: Schedule daily crawling of Michelin star data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  # 1: Crawl data
  crawl:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      # Upgrade pip
      - run: python3 -m pip install --upgrade pip
      # Install dependencies
      - run: pip3 install -r requirements.txt
      # Run crawl script
      - run: python index.py
      
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            data/michelin-star
      
      # Get current branch
      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
      
      - name: Commit and Push when any of the above files change
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      
          git add ./data/michelin-star
          git commit -m "actions: add new michelin star data"
          git push origin ${{ env.BRANCH_NAME }}
  
  # 2: Aggregate data
  aggregate:
    needs: crawl
    
    runs-on: ubuntu-latest

    permissions:
      contents: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'
      - run: python3 -m pip install --upgrade pip
      - run: pip3 install -r requirements.txt
      - run: python aggregator.py
      
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v12
        id: verify-changed-files
        with:
          files: |
            data
      
      - name: Get current branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Commit and Push when any of the above files change
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

          git add ./data
          git commit -m "actions: add aggregated data"
          git push origin ${{ env.BRANCH_NAME }}

  # 3: Load data into Google BigQuery
  load-data-into-gcb:
    needs: aggregate

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: 'pip'

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCB_CREDENTIALS }}" > gcb_credentials.json
      
      - run: python3 -m pip install --upgrade pip
      - run: pip3 install -r requirements.txt
      - run: python load_into_gcb.py gcb_credentials.json
